### ISSUE TITLE
Migrate to .NET 6

### ISSUE THREAD

**Issue by nogic1008** [nogic1008/dotnet-ci-example#91]
## Tasks
- [x] Change SDK to .NET 6.0 (#94)
- [x] Change Target Framework to `net6.0` (#94)
- [x] Change CI/CD workflow to use .NET 6.0 (#94)
- [x] C# 10 (#95)
- [x] Update Lint config (dotnet-format) (#96)
